# Generated by Django 2.2.10 on 2020-06-30 01:42

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
