# Generated by Django 2.2.10 on 2020-06-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20200630_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='video', max_length=100),
            preserve_default=False,
        ),
    ]
