# Generated by Django 2.2.10 on 2020-06-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default=1, upload_to='video-image'),
            preserve_default=False,
        ),
    ]
