# Generated by Django 2.2.10 on 2020-07-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.CharField(default='class Test(models.Model):', max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='desc',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='desc',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='desc',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vlog',
            name='desc',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
