# Generated by Django 2.2.10 on 2020-07-03 13:31

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20200702_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='recipe-media')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True)),
                ('desc', models.CharField(max_length=90)),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
            ],
        ),
    ]
