# Generated by Django 2.2.10 on 2020-07-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='mainiamge',
            new_name='image',
        ),
    ]
