# Generated by Django 2.2.10 on 2020-07-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20200703_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
