# Generated by Django 2.2.10 on 2020-07-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_restaurant_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vlog',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
