# Generated by Django 2.2.10 on 2020-07-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_auto_20200704_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='category',
            field=models.IntegerField(choices=[(1, 'Restaurant'), (2, 'Review'), (3, 'Vlog'), (4, 'Blog'), (5, 'Video'), (6, 'Recipe')], default=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model',
            name='rating',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], unique=True),
        ),
    ]
